version: "3"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db:
    driver: local
